In [17]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
from scipy.stats import zscore
from scipy.stats import chi2_contingency
from scipy.stats.contingency import association
import matplotlib.pyplot as plt

In [41]:
file_path = r'C:\Users\gijsv\OneDrive\Documenten\Ironhack\week5\Project\Data\Raw\df_final_demo.txt'
df_f_dem_original = pd.read_csv(file_path)
df_f_dem = df_f_dem_original.copy()

file_path = r'C:\Users\gijsv\OneDrive\Documenten\Ironhack\week5\Project\Data\Raw\df_final_experiment_clients.txt'
df_f_ex_original = pd.read_csv(file_path)
df_f_ex = df_f_ex_original.copy()

file_path = r'C:\Users\gijsv\OneDrive\Documenten\Ironhack\week5\Project\Data\Raw\df_final_web_data_pt_1.txt'
df_f_we1_original = pd.read_csv(file_path)
df_f_we1 = df_f_we1_original.copy()
df_f_we1

file_path = r'C:\Users\gijsv\OneDrive\Documenten\Ironhack\week5\Project\Data\Raw\df_final_web_data_pt_2.txt'
df_f_we2_original = pd.read_csv(file_path)
df_f_we2 = df_f_we2_original.copy()

concatenated_df = pd.concat([df_f_we1, df_f_we2], ignore_index=True)
df_f_we = concatenated_df.sort_values(by='date_time')

df_f_we

,client_id,visitor_id,visit_id,process_step,date_time
286566,9088444,242404224_96732670250,423038079_46067236368_400417,step_3,2017-03-15 00:03:03
35293,7179755,167765295_97487764427,264484508_5982901710_928530,start,2017-03-15 00:19:28
35292,7179755,167765295_97487764427,264484508_5982901710_928530,step_1,2017-03-15 00:20:50
35291,7179755,167765295_97487764427,264484508_5982901710_928530,step_2,2017-03-15 00:22:52
35290,7179755,167765295_97487764427,264484508_5982901710_928530,step_3,2017-03-15 00:23:47
...,...,...,...,...,...
519273,4159912,169591677_18042085072,358114812_31313949217_790854,start,2017-06-20 23:58:40
519272,4159912,169591677_18042085072,358114812_31313949217_790854,step_1,2017-06-20 23:59:00
519271,4159912,169591677_18042085072,358114812_31313949217_790854,step_2,2017-06-20 23:59:23
527151,5640210,854970757_75895258102,959123368_90077952691_695747,start,2017-06-20 23:59:53
670704,4227031,375803585_1924749079,694062705_73082073487_259240,start,2017-06-20 23:59:57